### ISSUE TITLE
Verify contract on Etherscan?

### ISSUE THREAD

**Issue by marsrobertson** [MetaMask/nft-tickets-workshop#4]
This is nice: https://github.com/rkalis/truffle-plugin-verify

Verified it here: https://rinkeby.etherscan.io/tx/0x8d591b9fb98727e8117f604c18cd56f0423db070cd5dd84905e956d7f5a7fb23

Since I've verified, it will be verified automatically...

**Comment by httpJunkie** [comment]
I will check this out, but I'm about to archive this repository as we have rebuilt this workshop here:
https://github.com/MetaMask/onchain-svg-nft-tickets
